---
title: "Markdown2"
output: html_document
---

# Lista 5

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp2)
library(ggplot2)
library(tseries)
load("C:/PENTES/Series_Temporais/aula1.RData")
```

Questão 1:

```{r}
autoplot(eggs)
```


```{r}
eggs.ses <- ses(eggs, h=100)
summary(eggs.ses)
```

```{r}
autoplot(eggs, series = "eggs") +
  autolayer(eggs.ses$fitted, series = "SES Forecast")
```

```{r}
autoplot(eggs)+
  autolayer(eggs.ses$mean)
```

```{r}
eggs.holt <-holt(eggs, h=100)
summary(eggs.holt)
```

```{r}
autoplot(eggs, series = "EGGS", col = "1")+
  autolayer(eggs.ses$fitted, series = "SES")+
  autolayer(eggs.holt$fitted, series = "HOLT")
```

```{r}
autoplot(eggs)+
  autolayer(eggs.ses$mean)+
  autolayer(eggs.holt$mean)
```

### b)
Segundo o RMSE, o método que dá o melhor valor é o do Modelo de Alisamento Exponêncial Simples, com 26.56

#### d)

```{r}
checkresiduals(eggs.ses$residuals)
```

```{r}
autoplot(books)
```

### b) SES

```{r}
paper.ses <- ses(books[,c("Paperback")], h=4)

hard.ses <- ses(books[,c("Hardcover")], h=4)

summary(paper.ses)
summary(hard.ses)
```

```{r}
autoplot(books[,c("Paperback")], series = "Paperback")+
  autolayer(paper.ses$mean)
```

```{r}
autoplot(books[,c("Hardcover")], series = "Hardcover")+
  autolayer(hard.ses$mean)
```

```{r}
paper.holt <- holt(books[,c("Paperback")], h=4)
hard.holt <- holt(books[,c("Hardcover")], h=4)
```

```{r}
paper.holtD <- holt(books[,c("Paperback")], h=4, damped = TRUE)
hard.holtD <- holt(books[,c("Hardcover")], h=4, damped = TRUE)
```

```{r}
accuracy(paper.ses$fitted, books[,c("Paperback")])[,c("RMSE")]
accuracy(paper.holt$fitted, books[,c("Paperback")])[,c("RMSE")]
accuracy(paper.holtD$fitted, books[,c("Paperback")])[,c("RMSE")]
```
```{r}
accuracy(hard.ses$fitted, books[,c("Hardcover")])[,c("RMSE")]
accuracy(hard.holt$fitted, books[,c("Hardcover")])[,c("RMSE")]
accuracy(hard.holtD$fitted, books[,c("Hardcover")])[,c("RMSE")]
```

```{r}
autoplot(books[,c("Paperback")], series = "Paperback")+
  autolayer(paper.ses$mean)+
  autolayer(paper.holt$mean)+
  autolayer(paper.holtD$mean)
```

```{r}
autoplot(books[,c("Hardcover")], series = "Hardcover")+
  autolayer(hard.ses$mean)+
  autolayer(hard.holt$mean)+
  autolayer(hard.holtD$mean)
```

## Questão 2

### a)

```{r}
autoplot(gas)
```

Porque a Amplitude Sazonal está aumentando com a tendência

### b)

```{r}
gas.HW.M <- hw(gas, seasonal = "multiplicative")
gas.HW.dM <- hw(gas, seasonal = "multiplicative", damped = TRUE)
```

```{r}
autoplot(gas)+
  autolayer(gas.HW.dM$fitted)+
  autolayer(gas.HW.M$fitted)
```

```{r}
accuracy(gas.HW.M)[,c("RMSE", "MAE", "MAPE")]
accuracy(gas.HW.dM)[,c("RMSE", "MAE", "MAPE")]
```
```{r}
checkresiduals(gas.HW.dM)
```

```{r}
bc.gas.hw <- hw(gas, lambda = "auto")
bc.gas.dhw <- hw(gas, lambda = "auto", damped = TRUE)
```

```{r}
accuracy(bc.gas.hw)[,c("RMSE", "MAE", "MAPE")]
accuracy(bc.gas.dhw)[,c("RMSE", "MAE", "MAPE")]
```
```{r}
checkresiduals(bc.gas.dhw)
```

### e)

```{r}
gas.1970 <- window(gas, start=c(1970,1), frequency = 12)
```

```{r}
gas.HW.M.1970 <- hw(gas.1970, seasonal = "multiplicative")
gas.HW.dM.1970 <- hw(gas.1970, seasonal = "multiplicative", damped = TRUE)
```

```{r}
accuracy(gas.HW.M.1970)[,c("RMSE", "MAE", "MAPE")]
accuracy(gas.HW.dM.1970)[,c("RMSE", "MAE", "MAPE")]
```
```{r}
checkresiduals(gas.HW.dM.1970)
```

```{r}
autoplot(gas.1970)+
  autolayer(gas.HW.dM.1970$fitted)
```


## Questão 4

```{r}
autoplot(ukcars)
```

```{r}
ggseasonplot(ukcars)
```

```{r}
rob <- test.Outliers.STL(ukcars)
stl.ukcars <- stl(ukcars, robust = rob, s.window = "periodic")

stl.ukcars.ss <- seasadj(stl.ukcars)

autoplot(stl.ukcars.ss)
```

### c)

```{r}
stl.ukcars.prev <- holt(stl.ukcars.ss, damped = TRUE, h=8)

stl.ukcars.prev$mean

stl.ukcars.prev.2 <- stlf(ukcars, robust = TRUE, h=8, etsmodel = "AAN", damped = TRUE, s.window = TRUE)

stl.ukcars.prev.2$mean
```

### d)

```{r}
stl.ukcars.prev.holt <- holt(stl.ukcars.ss, h=8)
```

### e)

```{r}
accuracy(stl.ukcars.prev.holt)[,c("RMSE")]
accuracy(stl.ukcars.prev)[,c("RMSE")]
```

### f)

```{r}
checkresiduals(stl.ukcars.prev)
```

## Questão 5

```{r}
autoplot(visitors)
```

```{r}
h<-24
n<-length(visitors)
train.visi<-ts(visitors[1:(n-h)], start=start(visitors), frequency = frequency(visitors))

test.visi<-ts(visitors[(n-h+1):n],end = end(visitors), frequency = frequency(visitors))
```

```{r}
length(test.visi)
```

```{r}
visi.hw <- holt(train.visi,h)

visi.hwd <- holt(train.visi, h, damped = TRUE)
```

### c)

```{r}
autoplot(train.visi)
```

### d)

```{r}
visi.snaive <- snaive(train.visi, h)
```

### e)

```{r}
accuracy(visi.hw$mean, test.visi)[,c("MAE", "RMSE", "MAPE")]
accuracy(visi.hwd$mean, test.visi)[,c("MAE", "RMSE", "MAPE")]
accuracy(visi.snaive$mean, test.visi)[,c("MAE", "RMSE", "MAPE")]
```

```{r}
checkresiduals(visi.snaive)
```



